### PR TITLE
[Modal] :bug: Changing Modal-size had no effect before

### LINKED ISSUE #4818: [BUG] Modal: width="small" reduserer padding som en utilsiktet sideeffekt
## Hva er feilen/problemet?

`width="small"` setter klassen `.aksel-modal--small` som overstyrer padding på header, body og footer – i tillegg til å sette bredden. Dette er udokumentert og uventet. Man forventer at `width` kun styrer bredde, og at `size` styrer tetthet/padding.

## Steg for å reprodusere problemet (valgfri)

1. Render `<Modal width="small">` med `Modal.Body`
2. Inspiser padding på `.aksel-modal__body` → `12px / 16px`
3. Sammenlign med `<Modal width={450}>` (samme bredde, numerisk) → `16px / 20px`

## Eksempel/Tilleggsinformasjon (valgfri)

**Workaround:** Bruk numerisk verdi (`width={480}`) for å få ønsket bredde uten padding-sideeffekten.

**Forslag:** Skill padding fra `width`-presets — `size` bør være den eneste prop-en som styrer tetthet.

### PR DESCRIPTION
**Pull request by KenAJoh**
### Description

Resolves #4818

### Component Checklist 📝

- [ ] JSDoc
- [ ] Examples
- [ ] Documentation / Decision Records
- [ ] Storybook
- [ ] Style mappings (`@navikt/core/css/config/_mappings.js`)
- [ ] CSS class deprecations (`@navikt/aksel-stylelint/src/deprecations.ts`)
- [ ] Exports (`@navikt/core/react/src/index.ts` and `@navikt/core/react/package.json`)
- [ ] New component? CSS import (`@navikt/core/css/index.css`)
- [ ] Breaking change? Update migration guide. Consider codemod.
- [ ] Changeset (Format: `<Component>: <gitmoji?> <Text>` E.g. "Button: :sparkles: Add feature xyz")

### CODE REVIEW

File: @navikt/core/react/src/modal/Modal.tsx [hunk 1]
```diff
@@ -93,6 +93,7 @@ export const Modal = forwardRef<HTMLDialogElement, ModalProps>(
       style,
       onClick,
       onMouseDown,
+      size = "medium",
```
Comment (HalvorHaugan) [inline @navikt/core/react/src/modal/Modal.tsx:96]: Maybe add `@default "medium"` in JSDoc

File: .changeset/chilly-llamas-show.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+"@navikt/ds-react": patch
+"@navikt/ds-css": patch
+---
+
+Modal: Changing modal-size had no effect before
```
Comment (HalvorHaugan) [inline .changeset/chilly-llamas-show.md]:
```suggestion
Modal: Changing `size` had no effect before
```
```suggestion
Modal: `size` prop now works
```

**Review by HalvorHaugan — DISMISSED** [review]
